language: rust

sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - rustup install nightly
  - rustup component add rustfmt-preview --toolchain nightly

script:
  - cargo +nightly fmt --verbose --all -- --check
  - cargo build --verbose --all
