language: rust

sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - rustup install nightly-2018-12-06
  - rustup component add clippy-preview --toolchain nightly-2018-12-06
  - rustup component add rustfmt-preview --toolchain nightly-2018-12-06

script:
  - cargo build --verbose --all-targets
  - cargo +nightly-2018-12-06 fmt --verbose --all -- --verbose --check
  - cargo +nightly-2018-12-06 clippy --verbose --all-targets

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
      cargo doc --all --no-deps --verbose &&
      echo "<meta http-equiv=refresh content=0;url=robar/index.html>" > target/doc/index.html &&
      git clone https://github.com/davisp/ghp-import.git &&
      ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/doc &&
      echo "Uploaded documentation"
    fi
