[global]
x_center_absolute = 100
y_center_absolute = 100
height_absolute = 100
width_absolute = 100
padding = 10
border = 10
margin = 10

[colors.default]
foreground = "#111111"
background = "#111111"
border = "#111111"
