[global]
x_center_absolute = 1000
y_center_absolute = 300
height_absolute = 200
width_absolute = 30
padding = 2
border = 3
margin = 2
fill_direction = "up"

[colors.default]
foreground = "#eee8e5"
background = "#073642"
border = "#b58900"
